language: ruby
rvm:
  - 2.1.1

sudo: false
cache: bundler

# Make build error instead of fail when validator.nu is down
before_install:
  - wget -O /dev/null http://validator.nu

install:
  - gem install html-proofer
  - npm install html5-lint

script:
  - htmlproof public/
  - htmlproof errors/
  - ./html5check.sh


after_success:
  - 'curl -s http://google.com/ping\?sitemap=http:%3A%2F%2Fsigurdhsson.org%2Fsitemap.xml > /dev/null'
