language: node_js
node_js:
  - "6"

sudo: false
cache: bundler

# Make build error instead of fail when validator.nu is down
before_install:
  - wget -O /dev/null http://validator.nu

install:
  - gem install html-proofer
  - npm install html5-lint
  - npm install npm-check

script:
  - htmlproof public/ --url-ignore 'https://linkedin.com/in/simonsigurdhsson/' # Looks like LinkedIn has some dumb scrape filter going on
  - htmlproof errors/
  - ./html5check.sh
  - npm-check


after_success:
  - 'curl -s http://google.com/ping\?sitemap=http:%3A%2F%2Fsigurdhsson.org%2Fsitemap.xml > /dev/null'

deploy:
  provider: heroku
  api_key:
    secure: V8A0CH4UGcjlcDJlgVYsDpZBYAmtnlOyqLkBAlqYY/5uGc4VBrpocX88lFRjk4R7h78d6VkiqdGOKWutSWOaa+h+/InI3pPgw4+tEcZBOyQxdW8FHeGlJPLN6m9ykwJ0/YTvB7Xa8oE+irOJGdCvGj6YS4AfBs2DuiRC4tD0LWo=
  app: urdh-hcard
  on:
    repo: urdh/hcard
